backend:
    name: git-gateway

publish_mode: editorial_workflow
media_folder: 'source/images'
public_folder: '/images'
media_library:
    name: cloudinary
    config:
        cloud_name: wkwkrnht
        api_key: 434895888337457
        config:
            enhance_image_tag: true
            static_file_support: true
            default_transformations:
                responsive: true
                fetch_format: auto

collections:
    - name: 'blog'
      label: 'Blog'
      folder: 'source/blog/articles'
      extension: '.html.md'
      format: frontmatter
      create: true
      slug: '{{title}}'
      fields:
        - {label: 'Title', name: 'title', widget: string, required: true}
        - {label: 'Publish Date', name: 'date', widget: datetime, required: true}
        - {label: 'Description', name: 'description', widget: string, required: false}
        - {label: 'Author', name: 'author', widget: string, default: 'wkwkrnht', required: true}
        - {label: 'Eyecatch', name: 'eyecatch', widget: image, required: false}
        - {label: 'Tags', name: tags, widget: 'list', default: ['未分類'], required: false}
        - {label: 'Body', name: 'body', widget: markdown, required: true}